"""
PV System Consumption Pattern Graphs - Version 2
Visualization for consumption patterns generated by the consumption generator
"""

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np
from typing import Dict, List, Optional, Tuple
from datetime import datetime, timedelta
from PV_consumption_generator import ConsumptionPatternGenerator, HouseholdProfile


class ConsumptionGraphGenerator:
    """Generate graphs for consumption patterns"""
    
    def __init__(self, generator: ConsumptionPatternGenerator):
        self.generator = generator
    
    def plot_daily_pattern_comparison(self, 
                                     profile: HouseholdProfile,
                                     save_path: Optional[str] = None,
                                     show: bool = True) -> plt.Figure:
        """
        Plot comparison of weekday vs weekend consumption patterns
        Shows typical daily consumption curves
        """
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
        fig.suptitle(f'Daily Consumption Patterns - {profile.name}', 
                    fontsize=14, fontweight='bold')
        
        hours = np.arange(24)
        
        # Winter weekday vs weekend
        winter_weekday = [self.generator.get_hourly_consumption(profile, 1, 0, h) for h in hours]
        winter_weekend = [self.generator.get_hourly_consumption(profile, 1, 5, h) for h in hours]
        
        ax1.plot(hours, winter_weekday, marker='o', linewidth=2, 
                label='Weekday (Mon)', color='blue')
        ax1.plot(hours, winter_weekend, marker='s', linewidth=2, 
                label='Weekend (Sat)', color='orange')
        ax1.fill_between(hours, winter_weekday, alpha=0.3, color='blue')
        ax1.fill_between(hours, winter_weekend, alpha=0.3, color='orange')
        
        ax1.set_xlabel('Hour of Day', fontsize=11, fontweight='bold')
        ax1.set_ylabel('Consumption (kWh)', fontsize=11, fontweight='bold')
        ax1.set_title('January (Winter) - Weekday vs Weekend', fontsize=12)
        ax1.legend(loc='upper left', fontsize=10)
        ax1.grid(True, alpha=0.3)
        ax1.set_xlim(0, 23)
        ax1.set_xticks(range(0, 24, 3))
        
        # Add time period labels
        ax1.axvspan(0, 6, alpha=0.1, color='navy', label='Night')
        ax1.axvspan(6, 9, alpha=0.1, color='yellow', label='Morning')
        ax1.axvspan(18, 23, alpha=0.1, color='red', label='Evening')
        
        # Summer weekday vs weekend
        summer_weekday = [self.generator.get_hourly_consumption(profile, 7, 0, h) for h in hours]
        summer_weekend = [self.generator.get_hourly_consumption(profile, 7, 5, h) for h in hours]
        
        ax2.plot(hours, summer_weekday, marker='o', linewidth=2, 
                label='Weekday (Mon)', color='blue')
        ax2.plot(hours, summer_weekend, marker='s', linewidth=2, 
                label='Weekend (Sat)', color='orange')
        ax2.fill_between(hours, summer_weekday, alpha=0.3, color='blue')
        ax2.fill_between(hours, summer_weekend, alpha=0.3, color='orange')
        
        ax2.set_xlabel('Hour of Day', fontsize=11, fontweight='bold')
        ax2.set_ylabel('Consumption (kWh)', fontsize=11, fontweight='bold')
        ax2.set_title('July (Summer) - Weekday vs Weekend', fontsize=12)
        ax2.legend(loc='upper left', fontsize=10)
        ax2.grid(True, alpha=0.3)
        ax2.set_xlim(0, 23)
        ax2.set_xticks(range(0, 24, 3))
        
        # Add time period labels
        ax2.axvspan(0, 6, alpha=0.1, color='navy')
        ax2.axvspan(6, 9, alpha=0.1, color='yellow')
        ax2.axvspan(18, 23, alpha=0.1, color='red')
        
        plt.tight_layout()
        
        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            print(f"Graph saved to: {save_path}")
        
        if show:
            plt.show()
        
        return fig
    
    def plot_seasonal_variation(self,
                               profile: HouseholdProfile,
                               save_path: Optional[str] = None,
                               show: bool = True) -> plt.Figure:
        """
        Plot seasonal consumption variation across the year
        Shows Gaussian curve with higher consumption in winter
        """
        fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 8))
        fig.suptitle(f'Seasonal Consumption Variation - {profile.name}', 
                    fontsize=14, fontweight='bold')
        
        months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 
                 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        month_nums = range(1, 13)
        
        # Monthly total consumption
        monthly_totals = []
        monthly_weekdays = []
        monthly_weekends = []
        
        days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
        
        for month, days in zip(month_nums, days_in_month):
            # Calculate average weekday and weekend for this month
            weekday_avg = self.generator.get_daily_consumption(profile, month, True)
            weekend_avg = self.generator.get_daily_consumption(profile, month, False)
            
            # Assume 22 weekdays, 8 weekend days per month (rough average)
            weekdays = 22
            weekends = days - weekdays
            
            monthly_total = (weekday_avg * weekdays) + (weekend_avg * weekends)
            monthly_totals.append(monthly_total)
            monthly_weekdays.append(weekday_avg)
            monthly_weekends.append(weekend_avg)
        
        # Plot 1: Monthly totals
        x_pos = np.arange(12)
        bars = ax1.bar(x_pos, monthly_totals, color='steelblue', alpha=0.7, edgecolor='navy')
        
        # Color code winter months differently
        winter_months = [0, 1, 2, 10, 11]  # Jan, Feb, Mar, Nov, Dec
        for i in winter_months:
            bars[i].set_color('darkblue')
            bars[i].set_alpha(0.8)
        
        # Add Gaussian curve overlay
        seasonal_curve = self.generator.generate_gaussian_seasonal_curve(
            peak_month=1,
            strength=profile.seasonal_strength
        )
        # Scale to match data
        base_monthly = profile.annual_consumption_kwh / 12
        curve_scaled = [base_monthly * m for m in seasonal_curve]
        
        ax1_twin = ax1.twinx()
        ax1_twin.plot(x_pos, curve_scaled, 'r--', linewidth=2, 
                     label='Gaussian Seasonal Curve', marker='o')
        ax1_twin.set_ylabel('Theoretical Monthly (kWh)', fontsize=10, color='red')
        ax1_twin.tick_params(axis='y', labelcolor='red')
        
        ax1.set_xlabel('Month', fontsize=11, fontweight='bold')
        ax1.set_ylabel('Monthly Consumption (kWh)', fontsize=11, fontweight='bold')
        ax1.set_title('Monthly Total Consumption with Gaussian Curve', fontsize=12)
        ax1.set_xticks(x_pos)
        ax1.set_xticklabels(months)
        ax1.grid(True, alpha=0.3, axis='y')
        
        # Add value labels on bars
        for i, (bar, val) in enumerate(zip(bars, monthly_totals)):
            height = bar.get_height()
            ax1.text(bar.get_x() + bar.get_width()/2., height,
                    f'{val:.0f}',
                    ha='center', va='bottom', fontsize=8)
        
        # Plot 2: Daily averages comparison
        x_pos2 = np.arange(12)
        width = 0.35
        
        bars1 = ax2.bar(x_pos2 - width/2, monthly_weekdays, width, 
                       label='Weekday Average', color='blue', alpha=0.7)
        bars2 = ax2.bar(x_pos2 + width/2, monthly_weekends, width, 
                       label='Weekend Average', color='orange', alpha=0.7)
        
        ax2.set_xlabel('Month', fontsize=11, fontweight='bold')
        ax2.set_ylabel('Daily Consumption (kWh)', fontsize=11, fontweight='bold')
        ax2.set_title('Average Daily Consumption - Weekday vs Weekend', fontsize=12)
        ax2.set_xticks(x_pos2)
        ax2.set_xticklabels(months)
        ax2.legend(loc='upper right', fontsize=10)
        ax2.grid(True, alpha=0.3, axis='y')
        
        # Highlight winter months
        for i in winter_months:
            ax2.axvspan(i-0.5, i+0.5, alpha=0.1, color='lightblue')
        
        plt.tight_layout()
        
        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            print(f"Graph saved to: {save_path}")
        
        if show:
            plt.show()
        
        return fig
    
    def plot_weekly_heatmap(self,
                           profile: HouseholdProfile,
                           month: int = 1,
                           save_path: Optional[str] = None,
                           show: bool = True) -> plt.Figure:
        """
        Create a heatmap of consumption over a week (24h x 7 days)
        """
        fig, ax = plt.subplots(figsize=(14, 6))
        
        month_names = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        
        fig.suptitle(f'Weekly Consumption Heatmap - {profile.name} ({month_names[month-1]})', 
                    fontsize=14, fontweight='bold')
        
        # Generate data for a week
        days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
        hours = np.arange(24)
        
        # Create 2D array: 7 days x 24 hours
        consumption_matrix = np.zeros((7, 24))
        
        for day in range(7):
            for hour in range(24):
                consumption_matrix[day, hour] = self.generator.get_hourly_consumption(
                    profile, month, day, hour
                )
        
        # Create heatmap
        im = ax.imshow(consumption_matrix, cmap='YlOrRd', aspect='auto', 
                      interpolation='bilinear')
        
        # Set ticks and labels
        ax.set_xticks(np.arange(24))
        ax.set_yticks(np.arange(7))
        ax.set_xticklabels([f'{h:02d}:00' for h in hours], fontsize=8)
        ax.set_yticklabels(days, fontsize=10)
        
        # Rotate the tick labels for better readability
        plt.setp(ax.get_xticklabels(), rotation=45, ha="right", rotation_mode="anchor")
        
        # Add colorbar
        cbar = plt.colorbar(im, ax=ax)
        cbar.set_label('Consumption (kWh)', rotation=270, labelpad=20, fontsize=11, fontweight='bold')
        
        # Add text annotations
        for day in range(7):
            for hour in range(24):
                value = consumption_matrix[day, hour]
                if value > 0.05:  # Only show significant values
                    text = ax.text(hour, day, f'{value:.2f}',
                                 ha="center", va="center", color="black", 
                                 fontsize=6, fontweight='bold')
        
        ax.set_xlabel('Hour of Day', fontsize=11, fontweight='bold')
        ax.set_ylabel('Day of Week', fontsize=11, fontweight='bold')
        
        # Add grid
        ax.set_xticks(np.arange(24) - 0.5, minor=True)
        ax.set_yticks(np.arange(7) - 0.5, minor=True)
        ax.grid(which="minor", color="white", linestyle='-', linewidth=1)
        
        # Highlight weekends
        ax.axhspan(4.5, 6.5, alpha=0.1, color='blue', zorder=0)
        
        plt.tight_layout()
        
        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            print(f"Graph saved to: {save_path}")
        
        if show:
            plt.show()
        
        return fig
    
    def plot_pattern_comparison(self,
                               patterns: List[str],
                               annual_consumption: float = 6000,
                               save_path: Optional[str] = None,
                               show: bool = True) -> plt.Figure:
        """
        Compare different consumption patterns (working family, retired, etc.)
        """
        fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(14, 10))
        fig.suptitle('Consumption Pattern Comparison', fontsize=14, fontweight='bold')
        
        hours = np.arange(24)
        colors = ['blue', 'orange', 'green', 'red', 'purple']
        
        # Create profiles for each pattern
        profiles = []
        for pattern in patterns:
            profile = self.generator.create_household_profile(
                name=pattern,
                annual_consumption_kwh=annual_consumption,
                pattern_type=pattern,
                seasonal_strength=0.5
            )
            profiles.append(profile)
        
        # Plot 1: Weekday patterns (winter)
        for i, profile in enumerate(profiles):
            pattern_data = [self.generator.get_hourly_consumption(profile, 1, 0, h) 
                          for h in hours]
            info = self.generator.get_pattern_info(profile.pattern_type)
            ax1.plot(hours, pattern_data, marker='o', linewidth=2, 
                    label=info['name'], color=colors[i % len(colors)])
        
        ax1.set_xlabel('Hour of Day', fontsize=10, fontweight='bold')
        ax1.set_ylabel('Consumption (kWh)', fontsize=10, fontweight='bold')
        ax1.set_title('January Weekday', fontsize=11)
        ax1.legend(loc='upper left', fontsize=8)
        ax1.grid(True, alpha=0.3)
        ax1.set_xlim(0, 23)
        
        # Plot 2: Weekend patterns (winter)
        for i, profile in enumerate(profiles):
            pattern_data = [self.generator.get_hourly_consumption(profile, 1, 5, h) 
                          for h in hours]
            info = self.generator.get_pattern_info(profile.pattern_type)
            ax2.plot(hours, pattern_data, marker='s', linewidth=2, 
                    label=info['name'], color=colors[i % len(colors)])
        
        ax2.set_xlabel('Hour of Day', fontsize=10, fontweight='bold')
        ax2.set_ylabel('Consumption (kWh)', fontsize=10, fontweight='bold')
        ax2.set_title('January Weekend', fontsize=11)
        ax2.legend(loc='upper left', fontsize=8)
        ax2.grid(True, alpha=0.3)
        ax2.set_xlim(0, 23)
        
        # Plot 3: Weekday patterns (summer)
        for i, profile in enumerate(profiles):
            pattern_data = [self.generator.get_hourly_consumption(profile, 7, 0, h) 
                          for h in hours]
            info = self.generator.get_pattern_info(profile.pattern_type)
            ax3.plot(hours, pattern_data, marker='o', linewidth=2, 
                    label=info['name'], color=colors[i % len(colors)])
        
        ax3.set_xlabel('Hour of Day', fontsize=10, fontweight='bold')
        ax3.set_ylabel('Consumption (kWh)', fontsize=10, fontweight='bold')
        ax3.set_title('July Weekday', fontsize=11)
        ax3.legend(loc='upper left', fontsize=8)
        ax3.grid(True, alpha=0.3)
        ax3.set_xlim(0, 23)
        
        # Plot 4: Monthly totals comparison
        months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 
                 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        x_pos = np.arange(12)
        width = 0.8 / len(profiles)
        
        for i, profile in enumerate(profiles):
            monthly_totals = []
            days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
            
            for month, days in zip(range(1, 13), days_in_month):
                weekday_avg = self.generator.get_daily_consumption(profile, month, True)
                weekend_avg = self.generator.get_daily_consumption(profile, month, False)
                
                # Approximate: 22 weekdays, rest weekends
                weekdays = 22
                weekends = days - weekdays
                
                monthly_total = (weekday_avg * weekdays) + (weekend_avg * weekends)
                monthly_totals.append(monthly_total)
            
            info = self.generator.get_pattern_info(profile.pattern_type)
            offset = (i - len(profiles)/2 + 0.5) * width
            ax4.bar(x_pos + offset, monthly_totals, width, 
                   label=info['name'], color=colors[i % len(colors)], alpha=0.7)
        
        ax4.set_xlabel('Month', fontsize=10, fontweight='bold')
        ax4.set_ylabel('Monthly Consumption (kWh)', fontsize=10, fontweight='bold')
        ax4.set_title('Monthly Consumption Comparison', fontsize=11)
        ax4.set_xticks(x_pos)
        ax4.set_xticklabels(months, fontsize=8)
        ax4.legend(loc='upper right', fontsize=8)
        ax4.grid(True, alpha=0.3, axis='y')
        
        plt.tight_layout()
        
        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            print(f"Graph saved to: {save_path}")
        
        if show:
            plt.show()
        
        return fig
    
    def plot_annual_overview(self,
                            profile: HouseholdProfile,
                            save_path: Optional[str] = None,
                            show: bool = True) -> plt.Figure:
        """
        Generate comprehensive annual overview with multiple metrics
        """
        fig = plt.figure(figsize=(14, 10))
        gs = fig.add_gridspec(3, 2, hspace=0.3, wspace=0.3)
        
        fig.suptitle(f'Annual Consumption Overview - {profile.name}', 
                    fontsize=14, fontweight='bold')
        
        # Generate full year data
        year_data = self.generator.generate_year_consumption(profile)
        stats = year_data['statistics']
        
        # Plot 1: Monthly totals
        ax1 = fig.add_subplot(gs[0, :])
        months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 
                 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        monthly_vals = [stats['monthly_totals'][i+1] for i in range(12)]
        
        bars = ax1.bar(range(12), monthly_vals, color='steelblue', alpha=0.7)
        bars[stats['peak_month']-1].set_color('darkred')
        bars[stats['low_month']-1].set_color('darkgreen')
        
        ax1.set_ylabel('Consumption (kWh)', fontsize=10, fontweight='bold')
        ax1.set_title('Monthly Consumption', fontsize=11)
        ax1.set_xticks(range(12))
        ax1.set_xticklabels(months)
        ax1.grid(True, alpha=0.3, axis='y')
        
        # Add value labels
        for i, (bar, val) in enumerate(zip(bars, monthly_vals)):
            ax1.text(bar.get_x() + bar.get_width()/2., bar.get_height(),
                    f'{val:.0f}', ha='center', va='bottom', fontsize=8)
        
        # Plot 2: Daily consumption over year
        ax2 = fig.add_subplot(gs[1, :])
        days = range(365)
        daily_vals = [d['daily_consumption_kwh'] for d in year_data['daily_data']]
        
        ax2.plot(days, daily_vals, linewidth=1, color='steelblue', alpha=0.7)
        ax2.fill_between(days, daily_vals, alpha=0.3, color='steelblue')
        
        # Mark weekends
        for i, d in enumerate(year_data['daily_data']):
            if not d['is_weekday']:
                ax2.axvline(i, color='orange', alpha=0.1, linewidth=0.5)
        
        ax2.set_xlabel('Day of Year', fontsize=10, fontweight='bold')
        ax2.set_ylabel('Daily Consumption (kWh)', fontsize=10, fontweight='bold')
        ax2.set_title('Daily Consumption Over Year (weekends highlighted)', fontsize=11)
        ax2.grid(True, alpha=0.3)
        ax2.set_xlim(0, 364)
        
        # Plot 3: Statistics summary
        ax3 = fig.add_subplot(gs[2, 0])
        ax3.axis('off')
        
        stats_text = f"""
CONSUMPTION STATISTICS

Annual Total: {stats['total_annual_kwh']:.0f} kWh
Average Daily: {stats['average_daily_kwh']:.2f} kWh
Average Monthly: {stats['total_annual_kwh']/12:.0f} kWh

Peak Month: {months[stats['peak_month']-1]}
Peak Consumption: {stats['monthly_totals'][stats['peak_month']]:.0f} kWh

Low Month: {months[stats['low_month']-1]}
Low Consumption: {stats['monthly_totals'][stats['low_month']]:.0f} kWh

Seasonal Variation: {(stats['monthly_totals'][stats['peak_month']] / stats['monthly_totals'][stats['low_month']]):.2f}x

Pattern Type: {profile.pattern_type}
Seasonal Strength: {profile.seasonal_strength:.1f}
"""
        
        ax3.text(0.1, 0.9, stats_text, transform=ax3.transAxes,
                fontsize=10, verticalalignment='top',
                bbox=dict(boxstyle='round,pad=1', facecolor='lightyellow', 
                         edgecolor='orange', linewidth=2),
                fontweight='bold', family='monospace')
        
        # Plot 4: Weekday vs Weekend comparison
        ax4 = fig.add_subplot(gs[2, 1])
        
        # Calculate average consumption by day of week
        day_names = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
        day_avgs = [0] * 7
        day_counts = [0] * 7
        
        for d in year_data['daily_data']:
            dow = d['day_of_week']
            day_avgs[dow] += d['daily_consumption_kwh']
            day_counts[dow] += 1
        
        day_avgs = [avg/count if count > 0 else 0 for avg, count in zip(day_avgs, day_counts)]
        
        colors_day = ['blue']*5 + ['orange']*2
        bars = ax4.bar(range(7), day_avgs, color=colors_day, alpha=0.7)
        
        ax4.set_ylabel('Avg Daily (kWh)', fontsize=10, fontweight='bold')
        ax4.set_title('Average by Day of Week', fontsize=11)
        ax4.set_xticks(range(7))
        ax4.set_xticklabels(day_names)
        ax4.grid(True, alpha=0.3, axis='y')
        
        # Add value labels
        for bar, val in zip(bars, day_avgs):
            ax4.text(bar.get_x() + bar.get_width()/2., bar.get_height(),
                    f'{val:.1f}', ha='center', va='bottom', fontsize=8)
        
        plt.tight_layout()
        
        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            print(f"Graph saved to: {save_path}")
        
        if show:
            plt.show()
        
        return fig


def main():
    """Example usage of consumption graph generator"""
    print("=" * 80)
    print("PV Consumption Pattern Graphs - Version 2")
    print("=" * 80)
    print()
    
    generator = ConsumptionPatternGenerator()
    graph_gen = ConsumptionGraphGenerator(generator)
    
    # Create example profile
    profile = generator.create_household_profile(
        name="Working Family",
        annual_consumption_kwh=6000,
        pattern_type='working_family',
        seasonal_strength=0.6,
        peak_hour=19
    )
    
    print("Generating graphs...")
    
    # Generate all graphs
    print("\n1. Daily pattern comparison (weekday vs weekend)...")
    graph_gen.plot_daily_pattern_comparison(profile, show=False)
    
    print("2. Seasonal variation...")
    graph_gen.plot_seasonal_variation(profile, show=False)
    
    print("3. Weekly heatmap...")
    graph_gen.plot_weekly_heatmap(profile, month=1, show=False)
    
    print("4. Pattern comparison...")
    patterns = ['working_family', 'home_office', 'retired']
    graph_gen.plot_pattern_comparison(patterns, show=False)
    
    print("5. Annual overview...")
    graph_gen.plot_annual_overview(profile, show=True)
    
    print("\nAll graphs generated successfully!")


if __name__ == "__main__":
    main()

